/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ChallengesSlugRouteImport } from './routes/challenges/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesSlugRoute = ChallengesSlugRouteImport.update({
  id: '/challenges/$slug',
  path: '/challenges/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/profile': typeof ProtectedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/profile': typeof ProtectedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/challenges': typeof ChallengesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get-started'
    | '/login'
    | '/onboarding'
    | '/sitemap.xml'
    | '/dashboard'
    | '/profile'
    | '/auth/callback'
    | '/blog/$slug'
    | '/challenges/$slug'
    | '/blog/'
    | '/challenges/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get-started'
    | '/login'
    | '/onboarding'
    | '/sitemap.xml'
    | '/dashboard'
    | '/profile'
    | '/auth/callback'
    | '/blog/$slug'
    | '/challenges/$slug'
    | '/blog'
    | '/challenges'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/get-started'
    | '/login'
    | '/onboarding'
    | '/sitemap.xml'
    | '/_protected/dashboard'
    | '/_protected/profile'
    | '/auth/callback'
    | '/blog/$slug'
    | '/challenges/$slug'
    | '/blog/'
    | '/challenges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  GetStartedRoute: typeof GetStartedRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ChallengesSlugRoute: typeof ChallengesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$slug': {
      id: '/challenges/$slug'
      path: '/challenges/$slug'
      fullPath: '/challenges/$slug'
      preLoaderRoute: typeof ChallengesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  GetStartedRoute: GetStartedRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogSlugRoute: BlogSlugRoute,
  ChallengesSlugRoute: ChallengesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './lib/router.ts'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
